// action types
export const ActionTypes = {
    SET_INITIAL_STATE: "SET_INITIAL_STATE",
    SET_APP_DEFAULT_LANGUAGE: "SET_APP_DEFAULT_LANGUAGE",
    SET_LOGGED_IN_USER_DATA: "SET_LOGGED_IN_USER_DATA",
    SET_GUEST_USER_DATA: "SET_GUEST_USER_DATA",
    UPDATE_DEVICE_TOKEN: "UPDATE_DEVICE_TOKEN",
    UPDATE_USER_DATA: "UPDATE_USER_DATA",
    UPDATE_GUEST_USER_DATA: "UPDATE_GUEST_USER_DATA",
};